### ISSUE TITLE
Think about log axis for convergence.png plot

### ISSUE THREAD

**Issue by MaGitTe** [MaGitTe/Numerical_Methods_in_Fluid_Mechanics#12]
Open Question in convergence.m
The assignment asks us to choose between plot, semilogx, semilogy, or loglog options for plotting the error against the gridsize. Which of these should we choose and why?
At the moment it is simply plot as this remains an open question.

**Comment by Younes-Toumi** [comment]
I just had a look at it, It seems we have the choice between the plotting styles. From my experience we often tends to choose a logarithmic scale when the variable increases/decreases rapidly (for ex. 1, 1/2, 1/4, 1/8 or 2, 4, 8, 16...etc). Since both dx_list and `e_1` have an important change in values, any of the four would be suitable (maybe with a sligh tendance for semilogy because we get the error in terms of powers of 10)

During the exercise class the instructor showed us plots from previous students, and I believe he showed us a figure containing four plots of the error (one with plot, one with semilogx, ...) so we can also plot them all 🤔

**Comment by MaGitTe** [comment]
We now plotted them all.
I believe logarithmic is especially helpfull, when looking at convergence for nonlinear cases comparing adjacent gridsizes
